# ~/.codex/config.toml 

approval_policy = "never"          # <- make edits without asking
model_reasoning_effort = "high"
sandbox_mode = "workspace-write"

[[trusted_workspaces]]
path = "/home/paul/DocsToKG"    # absolute path to your repo