name: ignored-by-path
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - ruff
  - black
  - mypy
  - pytest
  - pytest-cov
  - ipykernel
  - pre-commit
  - pip:
      - python-dotenv
