[project]
name = "DocsToKG"
version = "0.1.0"
description = "DocsToKG"
readme = "README.md"
requires-python = ">=3.12"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py313"
extend-select = ["I"]

[tool.mypy]
python_version = "3.13"
strict = true
