# Example resolver configuration illustrating new options.
resolver_order:
  - unpaywall
  - crossref
  - openaire
  - hal
  - osf
  - wayback

resolver_toggles:
  unpaywall: true
  crossref: true
  openaire: false
  hal: false
  osf: false
  wayback: true

resolver_min_interval_s:  # seconds between calls (e.g., 1.0 = max 1 QPS)
  unpaywall: 1.0
  crossref: 1.0
  openaire: 1.5

max_attempts_per_work: 10
timeout: 30.0

polite_headers:
  User-Agent: DocsToKGDownloader/1.0
mailto: research-ops@example.org

semantic_scholar_api_key: ${S2_API_KEY}
core_api_key: ${CORE_API_KEY}
