# Prometheus Configuration for OntologyDownload

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'production'
    service: 'ontology-download'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OntologyDownload application metrics
  - job_name: 'ontology-download'
    scrape_interval: 10s
    static_configs:
      - targets: ['ontology-download:8000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # DuckDB Catalog metrics
  - job_name: 'duckdb-catalog'
    scrape_interval: 30s
    static_configs:
      - targets: ['duckdb-catalog:8432']
    metrics_path: '/metrics'

  # Node Exporter (if available)
  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Docker Daemon (if available)
  - job_name: 'docker'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9323']
