"""Public API for the DocsToKG ontology downloader and resolver pipeline.

This facade exposes the primary fetch utilities used by external callers to
plan resolver fallback chains, download ontologies with hardened validation,
perform stream normalization, and emit schema-compliant manifests with
deterministic fingerprints.
"""

from __future__ import annotations

from .ontology_download import (
    CACHE_DIR,
    CONFIG_DIR,
    LOCAL_ONTOLOGY_DIR,
    LOG_DIR,
    MANIFEST_SCHEMA_VERSION,
    RDF_MIME_ALIASES,
    STORAGE,
    ConfigError,
    ConfigurationError,
    DefaultsConfig,
    DownloadFailure,
    DownloadResult,
    DownloadConfiguration,
    FetchResult,
    FetchSpec,
    OntologyDownloadError,
    PlannedFetch,
    ResolverCandidate,
    ResolvedConfig,
    ValidationConfig,
    ValidationRequest,
    ValidationResult,
    LoggingConfiguration,
    mask_sensitive_data,
    build_resolved_config,
    get_env_overrides,
    load_raw_yaml,
    merge_defaults,
    validate_config,
    download_stream,
    ensure_python_version,
    extract_archive_safe,
    fetch_all,
    fetch_one,
    generate_correlation_id,
    get_manifest_schema,
    get_owlready2,
    get_pronto,
    get_pystow,
    get_rdflib,
    load_config,
    plan_all,
    plan_one,
    parse_http_datetime,
    parse_iso_datetime,
    parse_rate_limit_to_rps,
    infer_version_timestamp,
    parse_version_timestamp,
    retry_with_backoff,
    run_validators,
    sanitize_filename,
    setup_logging,
    validate_manifest_dict,
    validate_url_security,
)

__all__ = [
    "FetchSpec",
    "FetchResult",
    "PlannedFetch",
    "DownloadResult",
    "DownloadFailure",
    "OntologyDownloadError",
    "ValidationRequest",
    "ValidationResult",
    "ResolverCandidate",
    "ResolvedConfig",
    "ConfigError",
    "ConfigurationError",
    "DefaultsConfig",
    "DownloadConfiguration",
    "ValidationConfig",
    "LoggingConfiguration",
    "build_resolved_config",
    "get_env_overrides",
    "load_raw_yaml",
    "merge_defaults",
    "validate_config",
    "CACHE_DIR",
    "CONFIG_DIR",
    "LOG_DIR",
    "LOCAL_ONTOLOGY_DIR",
    "STORAGE",
    "RDF_MIME_ALIASES",
    "MANIFEST_SCHEMA_VERSION",
    "fetch_one",
    "fetch_all",
    "plan_one",
    "plan_all",
    "download_stream",
    "extract_archive_safe",
    "validate_manifest_dict",
    "validate_url_security",
    "run_validators",
    "parse_iso_datetime",
    "parse_http_datetime",
    "parse_version_timestamp",
    "infer_version_timestamp",
    "setup_logging",
    "load_config",
    "ensure_python_version",
    "retry_with_backoff",
    "sanitize_filename",
    "generate_correlation_id",
    "parse_rate_limit_to_rps",
    "get_pystow",
    "get_rdflib",
    "get_pronto",
    "get_owlready2",
    "get_manifest_schema",
    "mask_sensitive_data",
]
