"""Public facade aggregating ontology downloader modules."""

from __future__ import annotations

from .config import (
    ConfigError,
    DefaultsConfig,
    DownloadConfiguration,
    LoggingConfiguration,
    ResolvedConfig,
    ValidationConfig,
    build_resolved_config,
    ensure_python_version,
    get_env_overrides,
    load_config,
    load_raw_yaml,
    parse_rate_limit_to_rps,
    validate_config,
)
from .io_safe import generate_correlation_id, mask_sensitive_data, sanitize_filename
from .net import (
    DownloadFailure,
    DownloadResult,
    RDF_MIME_ALIASES,
    RDF_MIME_FORMAT_LABELS,
    download_stream,
    extract_archive_safe,
    retry_with_backoff,
    sha256_file,
    validate_url_security,
)
from .optdeps import get_owlready2, get_pronto, get_pystow, get_rdflib
from .pipeline import (
    MANIFEST_JSON_SCHEMA,
    MANIFEST_SCHEMA_VERSION,
    ConfigurationError,
    FetchResult,
    FetchSpec,
    Manifest,
    OntologyDownloadError,
    PlannedFetch,
    ResolverCandidate,
    ResolverError,
    ValidationError,
    fetch_all,
    fetch_one,
    get_manifest_schema,
    infer_version_timestamp,
    merge_defaults,
    parse_http_datetime,
    parse_iso_datetime,
    parse_version_timestamp,
    plan_all,
    plan_one,
    setup_logging,
    validate_manifest_dict,
    _build_destination,
)
from .storage import CACHE_DIR, CONFIG_DIR, LOG_DIR, LOCAL_ONTOLOGY_DIR, STORAGE
from .validation_core import (
    ValidationRequest,
    ValidationResult,
    ValidationTimeout,
    ValidatorSubprocessError,
    normalize_streaming,
    run_validators,
    validate_arelle,
    validate_owlready2,
    validate_pronto,
    validate_rdflib,
    validate_robot,
    main as validation_main,
)

DefaultsConfiguration = DefaultsConfig
LoggingConfig = LoggingConfiguration
ValidationConfiguration = ValidationConfig


def main() -> None:
    """CLI entry point delegating to the validation worker."""

    validation_main()


__all__ = [
    "FetchSpec",
    "FetchResult",
    "PlannedFetch",
    "DownloadResult",
    "DownloadFailure",
    "OntologyDownloadError",
    "ValidationRequest",
    "ValidationResult",
    "ValidationTimeout",
    "ValidatorSubprocessError",
    "ResolverCandidate",
    "ResolvedConfig",
    "ConfigError",
    "ConfigurationError",
    "DefaultsConfig",
    "DownloadConfiguration",
    "ValidationConfig",
    "LoggingConfiguration",
    "build_resolved_config",
    "get_env_overrides",
    "load_raw_yaml",
    "merge_defaults",
    "validate_config",
    "CACHE_DIR",
    "CONFIG_DIR",
    "LOG_DIR",
    "LOCAL_ONTOLOGY_DIR",
    "STORAGE",
    "RDF_MIME_ALIASES",
    "MANIFEST_SCHEMA_VERSION",
    "MANIFEST_JSON_SCHEMA",
    "fetch_one",
    "fetch_all",
    "plan_one",
    "plan_all",
    "_build_destination",
    "download_stream",
    "extract_archive_safe",
    "validate_manifest_dict",
    "validate_url_security",
    "run_validators",
    "normalize_streaming",
    "validate_rdflib",
    "validate_pronto",
    "validate_owlready2",
    "validate_robot",
    "validate_arelle",
    "main",
    "parse_iso_datetime",
    "parse_http_datetime",
    "parse_version_timestamp",
    "infer_version_timestamp",
    "setup_logging",
    "load_config",
    "ensure_python_version",
    "retry_with_backoff",
    "sanitize_filename",
    "generate_correlation_id",
    "parse_rate_limit_to_rps",
    "get_pystow",
    "get_rdflib",
    "get_pronto",
    "get_owlready2",
    "get_manifest_schema",
    "mask_sensitive_data",
]
