# Example resolver configuration demonstrating selective HEAD disabling and
# MIME gating for known hosts that frequently misreport content types.

resolver_head_precheck:
  landing_page: false # disable HEAD preflight for the landing_page resolver

head_precheck_host_overrides:
  "www.sciencedirect.com": false
  "sciencedirect.com": false
  "onlinelibrary.wiley.com": false

domain_content_rules:
  "ieee.org":
    allowed_types: ["application/pdf"]
  "onlinelibrary.wiley.com":
    allowed_types: ["application/pdf"]
  "dl.acm.org":
    allowed_types: ["application/pdf"]

# Optional: configure circuit breaker policies shared with networking
breaker_config:
  defaults:
    fail_max: 5
    reset_timeout_s: 60
    retry_after_cap_s: 900
  hosts:
    "api.crossref.org":
      fail_max: 3
      reset_timeout_s: 90
      roles:
        artifact:
          trial_calls: 2
# breaker_config entries accept nested mappings or external YAML paths; see docs for details.
# Optional: host-specific Accept header overrides (uncomment if required)
# host_accept_overrides:
#   "onlinelibrary.wiley.com":
#     Accept: "application/pdf, */*;q=0.5"

# Wayback Machine rate limiting (recommended for polite crawling)
# Uncomment and adjust as needed for your use case
# rate_overrides:
#   - "web.archive.org.metadata=5/s,300/min"
#   - "web.archive.org.landing=3/s,180/min"
#   - "web.archive.org.artifact=1/s,60/min"
# rate_mode_overrides:
#   - "web.archive.org.metadata=wait:200"
#   - "web.archive.org.landing=wait:300"
#   - "web.archive.org.artifact=wait:1000"
