# Example resolver configuration demonstrating selective HEAD disabling and
# MIME gating for known hosts that frequently misreport content types.

resolver_head_precheck:
  landing_page: false  # disable HEAD preflight for the landing_page resolver

head_precheck_host_overrides:
  "www.sciencedirect.com": false
  "sciencedirect.com": false
  "onlinelibrary.wiley.com": false

domain_content_rules:
  "ieee.org":
    allowed_types: ["application/pdf"]
  "onlinelibrary.wiley.com":
    allowed_types: ["application/pdf"]
  "dl.acm.org":
    allowed_types: ["application/pdf"]

# Optional: host-specific Accept header overrides (uncomment if required)
# host_accept_overrides:
#   "onlinelibrary.wiley.com":
#     Accept: "application/pdf, */*;q=0.5"
