name: CI
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            DOCSTOKG_SKIP_GPU: "1" # tells tests to skip @pytest.mark.gpu paths
        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: false
                  fetch-depth: 1
              env:
                  GIT_LFS_SKIP_SMUDGE: "1"

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            # Optional: cache venv + pip (keeps CPU CI snappy)
            - name: Cache virtualenv
              id: cache-venv
              uses: actions/cache@v4
              with:
                  path: .venv
                  key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt','pyproject.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-
                  save-if: always()

            - name: Cache pip downloads
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt','pyproject.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-
                  save-if: always()

            - name: Install dependencies (CPU only)
              if: steps.cache-venv.outputs.cache-hit != 'true'
              shell: bash
              run: |
                  python -m venv .venv
                  source .venv/bin/activate
                  python -m pip install -U pip setuptools wheel
                  # requirements.txt should be CPU path: "-e ." plus test tools
                  pip install --no-cache-dir -r requirements.txt

            - name: Add virtualenv to PATH
              run: echo "${{ github.workspace }}/.venv/bin" >> "$GITHUB_PATH"

            - name: Run tests (skip GPU)
              shell: bash
              run: |
                  source .venv/bin/activate
                  python -V
                  pytest -q -m "not gpu"

            - name: HybridSearch validation CLI smoke test
              shell: bash
              run: |
                  source .venv/bin/activate
                  python -m DocsToKG.HybridSearch.validation --help
